apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf
resources:
  - ../../base/audiobookshelf
  # - cloudflare.yaml
  # - cloudflare-secret.yaml
  # - linkding-container-env-secret.yaml
  # - linkding-tls-secret.yaml
  # - ingress.yaml